// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("Authentication", Schema = "userMGT")]
public partial class Authentication
{
    [Key]
    [Column("user_id")]
    public int UserId { get; set; }

    [Required]
    [Column("password")]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("role")]
    public int? Role { get; set; }

    [Column("last_logged", TypeName = "datetime")]
    public DateTime LastLogged { get; set; }

    [Column("last_updated")]
    public byte[] LastUpdated { get; set; }

    [ForeignKey("Role")]
    [InverseProperty("Authentication")]
    public virtual Role RoleNavigation { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Authentication")]
    public virtual User User { get; set; }
}