// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("Authentication")]
[Index("Role", Name = "IX_Authentication_role")]
public partial class Authentication
{
    [Key]
    [Column("user_id")]
    public Guid UserId { get; set; }

    [Required]
    [Column("password")]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [Column("salt")]
    public byte[] Salt { get; set; }

    [Column("role")]
    public int? Role { get; set; }

    [Column("last_logged", TypeName = "datetime")]
    public DateTime LastLogged { get; set; }

    [Column("last_updated")]
    public DateTime LastUpdated { get; set; }

    [ForeignKey("Role")]
    [InverseProperty("Authentication")]
    public virtual Role RoleNavigation { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Authentication")]
    public virtual User User { get; set; }
}