// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("Calender_date")]
public partial class CalenderDate
{
    [Key]
    [Column("date", TypeName = "date")]
    public DateTime Date { get; set; }

    [Column("food_id")]
    public int? FoodId { get; set; }

    [ForeignKey("FoodId")]
    [InverseProperty("CalenderDate")]
    public virtual Food Food { get; set; }
}