// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[PrimaryKey("Date", "FoodId")]
[Table("Calender_date")]
[Index("FoodId", Name = "IX_Calender_date_food_id")]
public partial class CalenderDate
{
    [Key]
    [Column("date", TypeName = "date")]
    public DateTime Date { get; set; }

    [Key]
    [Column("food_id")]
    public Guid FoodId { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [ForeignKey("FoodId")]
    [InverseProperty("CalenderDate")]
    public virtual Food Food { get; set; }
}