// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("chat")]
public partial class Chat
{
    [Key]
    [Column("MessageID")]
    public Guid MessageId { get; set; }

    [Column("SenderID")]
    public Guid? SenderId { get; set; }

    [Column("ReceiverID")]
    public Guid? ReceiverId { get; set; }

    [Required]
    [Column("timestamp")]
    public byte[] Timestamp { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateTime { get; set; }

    [Unicode(false)]
    public string Message { get; set; }
}