// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("checkout")]
public partial class Checkout
{
    [Key]
    [Column("orderID")]
    [StringLength(10)]
    public string OrderId { get; set; }

    [Required]
    [Column("staffID")]
    [StringLength(10)]
    public string StaffId { get; set; }

    [Required]
    [Column("paymentMethod")]
    [StringLength(10)]
    public string PaymentMethod { get; set; }

    [Required]
    [StringLength(10)]
    public string Amount { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Checkout")]
    public virtual Orders Order { get; set; }
}