// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("Customer", Schema = "userMGT")]
public partial class Customer
{
    [Key]
    [Column("user_id")]
    public int UserId { get; set; }

    [Column("loyality_pts")]
    public int? LoyalityPts { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Reservation> Reservation { get; set; } = new List<Reservation>();

    [ForeignKey("UserId")]
    [InverseProperty("Customer")]
    public virtual User User { get; set; }
}