// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Keyless]
public partial class Dessert
{
    [Column("food_id")]
    public int FoodId { get; set; }

    [Column("dessert_id")]
    public int? DessertId { get; set; }

    [Column("served_temparature")]
    [StringLength(50)]
    [Unicode(false)]
    public string ServedTemparature { get; set; }
}