// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[PrimaryKey("UserId", "FoodId")]
[Table("Favorites", Schema = "userMGT")]
[Index("FoodId", Name = "IX_Favorites_food_id")]
public partial class Favorites
{
    [Key]
    [Column("user_id")]
    public int UserId { get; set; }

    [Key]
    [Column("food_id")]
    public int FoodId { get; set; }

    [ForeignKey("FoodId")]
    [InverseProperty("Favorites")]
    public virtual Food Food { get; set; }
}