// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace webapi.Models;

[Index("CategoryId", Name = "IX_Food_categoryID")]
public partial class Food
{
    [Key]
    [Column("food_id")]
    public Guid FoodId { get; set; }

    [Required]
    [Column("food_name")]
    [StringLength(100)]
    [Unicode(false)]
    public string FoodName { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("categoryID")]
    public int? CategoryId { get; set; }

    [Column("food_type")]
    [Unicode(false)]
    public string FoodType { get; set; }

    [Column("availability")]
    [StringLength(50)]
    [Unicode(false)]
    public string Availability { get; set; }

    [Column("price")]
    public double Price { get; set; }

    [Column("foodImg")]
    [Unicode(false)]
    public string FoodImg { get; set; }

    [NotMapped] // This property is not mapped to the database
    [DisplayName("Upload Image")]
    public IFormFile ImageFile { get; set; } // Used IFormFile for file uploads

    [InverseProperty("Food")]
    public virtual ICollection<CalenderDate> CalenderDate { get; set; } = new List<CalenderDate>();

    [ForeignKey("CategoryId")]
    [InverseProperty("Food")]
    public virtual FoodCategory Category { get; set; }

    [InverseProperty("Food")]
    public virtual ICollection<FoodUser> FoodUser { get; set; } = new List<FoodUser>();

    [InverseProperty("Food")]
    public virtual ICollection<MealFoods> MealFoods { get; set; } = new List<MealFoods>();

    [InverseProperty("Food")]
    public virtual ICollection<OrderFoods> OrderFoods { get; set; } = new List<OrderFoods>();
}