// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

public partial class FoodCategory
{
    [Key]
    [Column("categoryID")]
    [StringLength(10)]
    public string CategoryId { get; set; }

    [Required]
    [Column("categoryName")]
    [StringLength(50)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Food> Food { get; set; } = new List<Food>();
}