// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[PrimaryKey("FoodId", "CustomerId")]
[Index("CustomerId", Name = "IX_FoodUser_CustomerID")]
public partial class FoodUser
{
    [Key]
    public Guid FoodId { get; set; }

    [Key]
    [Column("CustomerID")]
    public Guid CustomerId { get; set; }

    public int? OrderCount { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("FoodUser")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("FoodId")]
    [InverseProperty("FoodUser")]
    public virtual Food Food { get; set; }
}