// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("Food_portions")]
public partial class FoodPortions
{
    [Key]
    [Column("food_id")]
    public int FoodId { get; set; }

    [Required]
    [Column("regular_price")]
    [StringLength(50)]
    public string RegularPrice { get; set; }

    [Column("large_price")]
    [StringLength(10)]
    public string LargePrice { get; set; }

    [ForeignKey("FoodId")]
    [InverseProperty("FoodPortions")]
    public virtual Food Food { get; set; }
}