// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Keyless]
[Table("Main_dish")]
public partial class MainDish
{
    [Column("food_id")]
    public int FoodId { get; set; }

    [Column("main_dish_id")]
    public int MainDishId { get; set; }
}