// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

public partial class Meal
{
    [Key]
    [Column("meal_id")]
    public Guid MealId { get; set; }

    [Column("meal_name")]
    [StringLength(255)]
    public string MealName { get; set; }

    [Column("discription")]
    [Unicode(false)]
    public string Discription { get; set; }

    [Column("price")]
    public double Price { get; set; }

    public bool? Custom { get; set; }

    [InverseProperty("Meal")]
    public virtual ICollection<MealFoods> MealFoods { get; set; } = new List<MealFoods>();

    [InverseProperty("Meal")]
    public virtual ICollection<OrderMeal> OrderMeal { get; set; } = new List<OrderMeal>();

    [ForeignKey("MealId")]
    [InverseProperty("Meal")]
    public virtual ICollection<Promotion> Promotion { get; set; } = new List<Promotion>();
}