// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

public partial class Meal
{
    [Key]
    [Column("meal_id")]
    [StringLength(10)]
    public string MealId { get; set; }

    [Column("meal_name")]
    public int MealName { get; set; }

    [Column("discription")]
    [Unicode(false)]
    public string Discription { get; set; }

    [Column("price")]
    public double Price { get; set; }

    [InverseProperty("Meal")]
    public virtual MealFoods MealFoods { get; set; }

    [ForeignKey("MealId")]
    [InverseProperty("Meal")]
    public virtual ICollection<Promotion> Promotion { get; set; } = new List<Promotion>();
}