// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("Meal_foods")]
[Index("FoodId", Name = "IX_Meal_foods_food_id")]
public partial class MealFoods
{
    [Key]
    [Column("meal_id")]
    [StringLength(10)]
    public string MealId { get; set; }

    [Column("food_id")]
    public int FoodId { get; set; }

    [Column("quantity1")]
    public int Quantity1 { get; set; }

    [Column("unit_price")]
    public double UnitPrice { get; set; }

    [ForeignKey("FoodId")]
    [InverseProperty("MealFoods")]
    public virtual Food Food { get; set; }

    [ForeignKey("MealId")]
    [InverseProperty("MealFoods")]
    public virtual Meal Meal { get; set; }
}