// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("orders")]
[Index("PromotionId", Name = "IX_orders_promotionID")]
[Index("ReservationId", Name = "IX_orders_reservation_id")]
public partial class Orders
{
    [Key]
    [Column("order_id")]
    public Guid OrderId { get; set; }

    [Column("reservation_id")]
    public Guid? ReservationId { get; set; }

    [Column("total")]
    public double Total { get; set; }

    [Column("discount")]
    public double? Discount { get; set; }

    [Column("price")]
    public double? Price { get; set; }

    [Required]
    [Column("order_status")]
    [StringLength(50)]
    public string OrderStatus { get; set; }

    [Column("promotionID")]
    public Guid? PromotionId { get; set; }

    [InverseProperty("Order")]
    public virtual Checkout Checkout { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderFoods> OrderFoods { get; set; } = new List<OrderFoods>();

    [InverseProperty("Order")]
    public virtual ICollection<OrderMeal> OrderMeal { get; set; } = new List<OrderMeal>();

    [ForeignKey("PromotionId")]
    [InverseProperty("Orders")]
    public virtual Promotion Promotion { get; set; }

    [ForeignKey("ReservationId")]
    [InverseProperty("Orders")]
    public virtual Reservation Reservation { get; set; }
}