// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[PrimaryKey("OrderId", "MealId")]
[Table("Order_Meal")]
public partial class OrderMeal
{
    [Key]
    [Column("order_id")]
    public Guid OrderId { get; set; }

    [Key]
    [Column("meal_id")]
    public Guid MealId { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [ForeignKey("MealId")]
    [InverseProperty("OrderMeal")]
    public virtual Meal Meal { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderMeal")]
    public virtual Orders Order { get; set; }
}