// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("promotion")]
public partial class Promotion
{
    [Key]
    [Column("promotionID")]
    public Guid PromotionId { get; set; }

    [Column("discount")]
    public int? Discount { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("deadline", TypeName = "date")]
    public DateTime? Deadline { get; set; }

    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [InverseProperty("Promotion")]
    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    [ForeignKey("PromotionId")]
    [InverseProperty("Promotion")]
    public virtual ICollection<Meal> Meal { get; set; } = new List<Meal>();
}