// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Index("TableNo", Name = "IX_Reservation_tableNo")]
public partial class Reservation
{
    [Key]
    [Column("reservation_id")]
    [StringLength(10)]
    public string ReservationId { get; set; }

    [Column("customer_id")]
    public Guid CustomerId { get; set; }

    [Column("staff_id")]
    public Guid StaffId { get; set; }

    [Column("tableNo")]
    public int TableNo { get; set; }

    [Column("reservation_datetime", TypeName = "datetime")]
    public DateTime? ReservationDatetime { get; set; }

    [Column("departure", TypeName = "datetime")]
    public DateTime? Departure { get; set; }

    [Required]
    [Column("actual_departure")]
    public byte[] ActualDeparture { get; set; }

    //[ForeignKey("CustomerId")]
    //[InverseProperty("Reservation")]
    //public virtual Customer Customer { get; set; }

    //uncomment later

    //[InverseProperty("Reservation")]
    //public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    //[ForeignKey("StaffId")]
    //[InverseProperty("Reservation")]
    //public virtual Staff Staff { get; set; }

    //[ForeignKey("TableNo")]
    //[InverseProperty("Reservation")]
    //public virtual Table TableNoNavigation { get; set; }
}