// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Table("Staff", Schema = "userMGT")]
public partial class Staff
{
    [Key]
    [Column("user_id")]
    public Guid UserId { get; set; }

    [Column("job_title")]
    [StringLength(50)]
    [Unicode(false)]
    public string JobTitle { get; set; }

    [Column("is_active")]
    public byte? IsActive { get; set; }

    [InverseProperty("Staff")]
    public virtual ICollection<Reservation> Reservation { get; set; } = new List<Reservation>();
}