// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models;

[Keyless]
public partial class UserAccounts
{
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("username")]
    [StringLength(10)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [Column("email")]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("password")]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("role")]
    public int? Role { get; set; }

    [Column("created_date", TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [Column("last_logged", TypeName = "datetime")]
    public DateTime LastLogged { get; set; }

    [Column("last_updated")]
    public byte[] LastUpdated { get; set; }
}